---
- name: Restart Apache Server
  hosts: webservers
  become: true
  become_user: root
  tasks:
    - name: Restart the apache2 server
      service: 
        name: apache2
        state: restarted
      # command: service apache2 restart
